name: Ci CD Pipeline

on:
    push:
        branches:
            - feature/**
        paths-ignore:
            - 'docs/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Extract Environment from Branch Name
              run: |
                  if [[ "${GITHUB_REF#refs/heads/}" == feature/* ]]; then
                     echo "ENVIRONMENT=feature-${GITHUB_REF#refs/heads/feature/}" >> $GITHUB_ENV
                     BRANCH_NAME=${GITHUB_REF#refs/heads/}
                     TEAM_NAME=$(echo $BRANCH_NAME | cut -d'/' -f2)
                     BRANCH_NAME_TEAM=$(echo $BRANCH_NAME | cut -d'/' -f3) 
                  fi
                  echo "TEAM_NAME=$TEAM_NAME"
                  NAMESPACE=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
                  echo $NAMESPACE
                  echo "TEAM_NAME=$TEAM_NAME" >> $GITHUB_ENV
                  echo "BRANCH_NAME_TEAM=$BRANCH_NAME_TEAM" >> $GITHUB_ENV
            # Step 2: Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image
              run: |
                  docker build -t 19910821/products-microservice:$TEAM_NAME-$BRANCH_NAME_TEAM-${{ github.sha }} .
                  docker tag 19910821/products-microservice:$TEAM_NAME-$BRANCH_NAME_TEAM-${{ github.sha }}  19910821/products-microservice:$TEAM_NAME-$BRANCH_NAME_TEAM-${{ github.sha }}
            - name: Push Docker Image
              run: |
                  docker push 19910821/products-microservice:$TEAM_NAME-$BRANCH_NAME_TEAM-${{ github.sha }}
